#!/bin/bash

files=`find ./src -type f -name "*.go" |xargs`
for file in $files; do
    gofmt -w=true ${file}
done

rm -f ./bin/lesscreator

go build -ldflags "-w -s" -o ./bin/lesscreator ./src/main.go

./bin/lesscreator 

