#!/bin/sh

set -e

chmod +x {pandora_userappdir}/bin/lesscreator

install -m 0755 -d {pandora_userdir}/conf/lesscreator
install -m 0644 -p {pandora_userappdir}/misc/etc/creator.json {pandora_userdir}/conf/lesscreator/creator.json

pandora-env-filter {pandora_userdir}/conf/lesscreator/creator.json


