#!/bin/bash

echo "DIRs"
find . -type d  | wc -l
echo "FILEs"
find . -type f  | wc -l
echo "LINEs"
find . -name "*.go" |xargs cat|grep -v ^$|wc -l
echo "DETAILs"
find . -type f -name "*.go" | xargs wc -l | sort -n

dirs=`find . -type d |xargs`
for dir in $dirs; do
    echo ${dir}
#    gofmt -tabwidth=4 -tabs=false -w=true ${dir}/*.go
done
#find . -type f -name "*.go" |xargs sed -i 's/\t/    /g'

rm -f h5creator-server

go build -o h5creator-server server.go 

./h5creator-server

