#!/usr/bin/php

<?php

// deps
//  xcftool 
//  imagemagick
//  optipng

$opt = getopt("s:l:L:b:gf");

$size = isset($opt['s']) ? intval($opt['s']) : die("NO -s size\n"); 
if ($size < 16) {
    die("InValid -s size\n"); 
}

$full = isset($opt['f']) ? true : false;
$bgrd = isset($opt['g']) ? true : false;
if ($bgrd) {
    $full = true;
}

$bdrs = isset($opt['b']) ? str_replace(" ", "", $opt['b']) : null;
$bdrs = strlen($bdrs) > 1 ? explode(",", $bdrs) : array();

$lyrs = isset($opt['l']) ? str_replace(" ", "", $opt['l']) : "";
$lyrs = explode(",", $lyrs);

$dir = __DIR__;

if (in_array('all', $lyrs)) {

    $cmd = "xcfinfo {$dir}/ico-base.xcf";
    $op = explode("\n", trim(shell_exec($cmd)));
    foreach ($op as $v) {
    
        if (!preg_match("/Normal\ +ico\-(.*?)$/", $v, $mat)) {
            continue;
        }
        
        if (!in_array("ico-". $mat[1], $lyrs)) {
            $lyrs[] = "ico-". $mat[1];
        }   
    }
}

foreach ($lyrs as $lyr) {

    if ($lyr == "all" || strlen($lyr) < 2) {
        continue;
    }

    if (substr($lyr, 0, 4) == "ico-") {
        $outfile = substr($lyr, 4);
    } else {
        $outfile = $lyr;
    }
    
    $outfile = $dir ."/../x/{$outfile}-{$size}.png";
    if (file_exists($outfile)) {
        continue;
    }
    
    if ($bgrd && substr($lyr, 0, 4) == "ico-") {
        if (substr($lyr, -6) == "-white") {
            $lyr .= " bg-o-white";
        } else {
            $lyr .= " bg-o";
        }
    }
    
    if (count($bdrs) > 0) {
        $lyr .= " ". implode(" ", $bdrs);
    }
    
    if ($full) {
        $cmd = "xcf2png -o {$outfile} {$dir}/ico-base.xcf {$lyr}";
    } else {
        $cmd = "xcf2png -O 150,150 -S 700x700 -o {$outfile} {$dir}/ico-base.xcf {$lyr}";
    }
    shell_exec($cmd);
    
    $cmd = "convert -resize {$size}x{$size} $outfile $outfile";
    shell_exec($cmd);
    
    $cmd = "optipng -o7 $outfile";
    shell_exec($cmd);

    echo "\t$lyr DONE\n";
}

