export PS1='\[\e[1;32m\][\u@\h \W]\$\[\e[0m\] '
export PS2='> '
export PS4='+ '

export LANG=en_US.UTF-8
export TERM=linux
export USER=`whoami`
export HOME={{.lessfly_userdir}}

cd ~

if [ `uname` = FreeBSD ]; then
	export PATH=$PATH:/usr/local/bin
	alias ls='ls -G'
fi

if [ `uname` = Linux ]; then
	alias ls='ls --color'
	alias ll='ls -l'
fi

if [ `uname` = Darwin ]; then
	alias ls='ls -G'
fi

echo Welcome to lessCreator Service'!'

